;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="GA.Shoot.changeAmmo",NewTagName="GA.Shoot.Reload")
+GameplayTagList=(Tag="Character.C_Weapon",DevComment="")
+GameplayTagList=(Tag="Character.C_Weapon.Primary",DevComment="")
+GameplayTagList=(Tag="Character.C_Weapon.Second",DevComment="")
+GameplayTagList=(Tag="Character.C_Weapon.Third",DevComment="")
+GameplayTagList=(Tag="Character.Killer",DevComment="")
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Cooldown.LevelBegin",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Health",DevComment="")
+GameplayTagList=(Tag="Effect.HitReaction",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.Changed",DevComment="")
+GameplayTagList=(Tag="Event.ActiveAbility.Dash",DevComment="")
+GameplayTagList=(Tag="Event.ActiveAbility.EquipWeapon",DevComment="")
+GameplayTagList=(Tag="Event.ActiveAbility.GetHit",DevComment="")
+GameplayTagList=(Tag="Event.ActiveAbility.Reload",DevComment="")
+GameplayTagList=(Tag="Event.ActiveAbility.Shoot",DevComment="")
+GameplayTagList=(Tag="Event.Death",DevComment="")
+GameplayTagList=(Tag="GA.Active",DevComment="")
+GameplayTagList=(Tag="GA.Begin",DevComment="")
+GameplayTagList=(Tag="GA.Death",DevComment="")
+GameplayTagList=(Tag="GA.HitReaction",DevComment="")
+GameplayTagList=(Tag="GA.Mov.Dash",DevComment="")
+GameplayTagList=(Tag="GA.Mov.PickUp",DevComment="")
+GameplayTagList=(Tag="GA.Revive",DevComment="")
+GameplayTagList=(Tag="GA.Shoot",DevComment="")
+GameplayTagList=(Tag="GA.Shoot.Aim",DevComment="")
+GameplayTagList=(Tag="GA.Shoot.Firing",DevComment="")
+GameplayTagList=(Tag="GA.Shoot.Reload",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.GetShoot",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash.Active",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Death",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Heal.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Shoot",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Shoot.Fire",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Shoot.Pick",DevComment="")
+GameplayTagList=(Tag="State.Death",DevComment="")
+GameplayTagList=(Tag="State.Respawn",DevComment="")
+GameplayTagList=(Tag="Status.Death",DevComment="")
+GameplayTagList=(Tag="Status.Remaina.Regen",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee.Knife",DevComment="")
+GameplayTagList=(Tag="Weapon.Range.Pistol",DevComment="")
+GameplayTagList=(Tag="Weapon.Range.Rifle",DevComment="")
+GameplayTagList=(Tag="Weapon.Range.Virtus",DevComment="")

